name: assetarchiverflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1 
  flutter_animate: ^4.5.2
  http: ^1.5.0
  url_launcher: ^6.2.6
  slide_to_act: ^2.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^6.0.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
